---
- name: Install Lamp
  hosts: webserver
  vars_files:
    - vars_lamp.yaml
  become: true #sudo
  gather_facts: "{{ facts }}"
  tasks:
    - block:
        - name: Install apache on CentOS
          when: ansible_facts['pkg_mgr'] == "dnf"
          dnf:
            name: "{{ apache_package_name }}"
            state: latest

        - name: Start & Enable Apache
          when: ansible_facts['service_mgr'] == "systemd"
          systemd:
            name: "{{ apache_service_name }}"
            state: started
            enabled: yes

        - name: Install PHP & Dependencies
          when: ansible_facts['pkg_mgr'] == "dnf"
          dnf:
            name: "{{ php_packages }}"
            state: latest

        - name: Install Wordpress
          unarchive:
            src: https://wordpress.org/latest.tar.gz
            dest: /tmp/
            remote_src: yes

        - name: Copy Wordpress files to /var/www/html/
          copy:
            src: /tmp/wordpress/
            dest: /var/www/html/
            remote_src: yes


        - name: Change ownership of /var/www/html
          file:
            path: /var/www/html
            state: directory
            recurse: yes
            owner: apache
            group: apache
          notify: Restart Apache

        - name:
          systemd:
            state: restarted
            name: httpd


      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "8"

  
  handlers:
    - name: Restart Apache
      systemd:
        name: "{{ apache_service_name }}"
        state: restarted
    
