---
- name: update all packages
  hosts: webserver
  gather_facts: yes
  become: true
  tasks:
    - name: update packages
      when: ansible_facts['pkg_mgr'] == "dnf"
      dnf:
        name: "*"
        state: latest