---
- name: User add 
  hosts: webserver
  gather_facts: no
  tasks:
    - name: add user
      user:
        name: ansible
        uid: 2500
        groups: ["wheel"]
    - name: Add a public key
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"





        